### ISSUE TITLE
NoConnectorUnitError

### ISSUE THREAD

**Issue by Prasoon6667** [akretion/connector-search-engine#19]
I have trouble in connecting with Algolia. 

 May be I have   wrongly configured backend connector. I have given values for location field as algolia.com, username as my_app_id and password as secret_api_key. Is this the way to configure ? 

I am getting the below error while exporting product to Algolia from the scheduler.

_Traceback (most recent call last):

  _File "C:\odoo\odoo-10\odoo\addons\base\ir\ir_cron.py", line 118, in _callback
    getattr(model, method_name)(*args)
  File "C:\odoo\odoo-10\addons-extra\connector_nosql\models\nosql_model.py", line 98, in _scheduler_export
    return self.search(domain).export_with_delay(batch_size)
  File "C:\odoo\odoo-10\addons-extra\connector_nosql\models\nosql_model.py", line 111, in export_with_delay
    exporter = env.get_connector_unit(NosqlExporter)
  File "C:\odoo\odoo-10\addons-extra\connector\connector.py", line 312, in get_connector_unit
    self.model_name)(self)
  File "C:\odoo\odoo-10\addons-extra\connector\backend.py", line 269, in get_class
    (base_class, session, model_name))
NoConnectorUnitError: No matching class found for <class_ 'odoo.addons.connector_nosql.unit.exporter.NosqlExporter'>_

**Comment by sebastienbeau** [comment]
Hi I think you are using the branch 9.0. I have done some clean up to the branches and set the 9.0 as deprecated. The 9.0 branch was obsolete as I have done a lot of change in 8.0 version. If you want to use the Algolia connector, please fork the 8.0 branch to migrate it to 10

If you need help ask, even if I am really busy but I will try to me best to help you.
