### ISSUE TITLE
refactor toward bulk update

### ISSUE THREAD

**Issue by rvalyi** [akretion/connector-search-engine#4]
the connector framework by CampToCamp is really nice and full featured. But half of it is overkill for solerp: we don't need really the mapper infrastructure for instance because we mostly denormalize records the same no matter their class. It's not like in Magento where exporting a partner is totally different from exporting a product and requires totally different code.

Instead, it would be really really nice if we could have a bulk synchronization instead of per record sync'.

Here is the plan:
## A) Changes to be made in upstream OCA Connector

1) have batch observers decorator inside Connector:
we should change connector/connector/producer.py to have consumers for batch write at least.
Bulk delete could be cool too. Batch create isn't supported by Odoo. A way to have batch create with Solerp would be to disable sync' during possible pseudo bulk creation of records in Odoo and then have a bulk write.

2) we would then optionally use different listeners in our concrete implementations. Instead of:

```
@on_record_write(model_names='product.product')
def solr_product_modified(session, model_name, record_id, vals):
    export_record.delay(session, model_name, record_id)
```

we would have a collection of ids.

3) in unit/export_synchronizer.py
where we have

```
def run(self, binding_id, *args, **kwargs):
```

we would have a collection of binding ids.

The concrete implementation of run would use these ids in batch or just loop over the several ids if their connector API doesn't support bulk update.
## B) inside Solerp specifically

in solerp/unit/export_synchronizer.py, where we have:

```
        map_record = self.mapper.map_record(self.binding_record)
        record = self._create_data(map_record, **kwargs)
```

we would typically bypass the mapper totally. Instead the code that is currently inside the mapper would be moved to orm.AbstractModel and eventually get bits overridden in some specific classes. The mapper would be batch oriented, that would require some rewrites but that should be doable.

Then we would still do `SolRExportSynchronizer.add(self.backend_record.location.encode('utf-8'), record)` because with the current code, the exports already only triggers after a given NUMBER_OF_DOCS_PER_ADD or after a certain amount of time. But we could also add a collection directly.

**Comment by sebastienbeau** [comment]
I close this issues as we have implemented a batch export not linked to the write
