### ISSUE TITLE
[12.0] body as required but in view is not visible....

### ISSUE THREAD

**Issue by hustlercoder** [akretion/connector-search-engine#58]

**Comment by simahawk** [comment]
what do you mean?

**Comment by hustlercoder** [comment]
The field body si required in the python code but in the xml is absent.When you try to create a configuration for an index an error is throwed and says: body is marked as required...but in the xml code the field is not visibile so not visible also on the ui

**Comment by simahawk** [comment]
@hustlercoder the repo has been moved to https://github.com/OCA/search-engine.
Can you try w/ latest version there? Also I don't think you are supposed to add indexes manually anymore as in the new version they are created automatically based on languages.
Feel free to open a new issue over there if needed.

**Comment by simahawk** [comment]
@sebastienbeau can you close this repo issue tracker?

**Comment by rvalyi** [comment]
@simahawk I'm closing it
