### ISSUE TITLE
[VERSIONS] Which one is the version I should use

### ISSUE THREAD

**Issue by nhomar** [akretion/connector-search-engine#8]
Hello Dude.

I want to give a try (I have a little need that I supose this module can solve).

Are you mantaining master or 8.0?

Which one I should fork to start testing?

Are you planning put this under OCE (I can make the job of prepare it you save me the starting point at least ;-)).

Do you have some roadmap to see how can we help to use it and improve it following your path (or both)?

Regards.

**Comment by rvalyi** [comment]
@nhomar we are maintaining both. But in fact master is 7.0. I'll change the name. You should go with 8.0.
Also this is going to be a pillar of our e-commerce / Locomotive solution. But you can use solr for simple indexation of all Odoo records of course and advanced search is certainly a possible application.

**Comment by sebastienbeau** [comment]
Issue deprecated due to all change done in 8.0 branch and for now solr version is not more supported
